### ISSUE TITLE
generated header file doesn't compile in c++ file.

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol-tools-bin#1]
Looks like C allows casts from enum types implicitly, but C++ doesn't?
Tested by changing cube-sapp into a .cc file. (Using VS 2017, Win10)

error C2440: 'initializing': cannot convert from 'int' to 'sg_uniform_type' 
note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)

error C2440: 'initializing': cannot convert from 'int' to 'sg_image_type' 
 note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)

(and a few more)

**Comment by floooh** [comment]
Argh, yes, that's the "explicit zero-initialization" I had to do for the sg_shader_desc structs.

Fix incoming...

**Comment by floooh** [comment]
Ok, should be fixed now, but I tested only on clang so far.

```./fips update``` in your project to update sokol-tools-bin, followed by ```./fips clean``` and ```./fips build```.

PS: if you see any other C++ compatibility errors, feel free to reopen this ticket with new details :)

**Comment by mattiasljungstrom** [comment]
Tested on VS2017 C++ now and works, thanks for quick update!
